### ISSUE TITLE
Not sure how to use SCAD files

### ISSUE THREAD

**Issue by fionnafire** [cy384/ppk_usb#11]
I know this is pretty old, but can you please provide a more universal file such as an STL please?

**Comment by fionnafire** [comment]
oof. I have hardly used Github

**Comment by cy384** [comment]
thanks for your interest, the files can be opened with [OpenSCAD](http://www.openscad.org/), and it's pretty easy to generate an STL.  As I'm traveling right now, it might be a few days, but I'll upload some as soon as I can.

**Comment by fionnafire** [comment]
thank you very much! I can't wait to get this thing working on my phone.

**Comment by cy384** [comment]
Sorry for the delayed response, coursework has kept me very busy for the past two months (finals ended yesterday).  [I've added a 1.0.0 release and attached the compiled STLs.](https://github.com/cy384/ppk_usb/releases/tag/v1.0.0)

If you need to tweak the files, you can also try pasting the code into [this in-broswer openscad.](http://openscad.net/)

**Comment by fionnafire** [comment]
Thank you so much. You of course had no obligation to make the STL files for me, I really appreciate your work!

I hope your finals went well, and honestly my own college and work schedule would have kept me from being able to make this thing myself anyway. So no worries about the delay.
