### ISSUE TITLE
Is it real to connect palm keyboard to PC rs232 (on ms dos)?

### ISSUE THREAD

**Issue by be3max** [cy384/ppk_usb#12]
Is it real to connect palm keyboard to PC rs232 (on ms dos)? I`m own old [HP 200lx](https://en.wikipedia.org/wiki/HP_200LX) that's have a rs232 port, these handledPC work on ms dos, and i searching info about keyboard connection on rs232. 
HP 200lx can connect with [Apple Newton keyboard](http://www.palmtoppaper.com/ptphtml/36/pt360021.htm) + driver, but which hard to find nowadays :(

**Comment by cy384** [comment]
That looks like a cool device!

Can it conceivably be done? I suspect yes.  Do I have any idea how to do it? Nope!  It would probably also need a special driver, in addition to figuring out the wiring.

Sorry I can't help, I hope you figure something out and can keep the old hardware alive.
