### ISSUE TITLE
keyboard.h

### ISSUE THREAD

**Issue by CableGuy67** [cy384/ppk_usb#14]
I finally sat down to finish this project and it went about as smooth as could be. So thanks for all your work!

The only issue I had with Arduino 1.8.5 and building for a Pro Micro (ish, from ebay) I had to add:
`#include <Keyboard.h>`
just after the SoftwareSerial include to get it to compile. After that, I was able to upload  the sketch and type this out on my old Palm keyboard.
![ppk1](https://user-images.githubusercontent.com/504816/57986131-9cb12f80-7a79-11e9-8525-653cb62e5b97.jpg)
![ppk2](https://user-images.githubusercontent.com/504816/57986141-beaab200-7a79-11e9-93e1-62c434c1ddcf.jpg)

**Comment by cy384** [comment]
it's very encouraging to see a successful build, thanks for sharing!  I've added the header in the last commit.
