### ISSUE TITLE
Pin 15 non-existent on arduino Leonardo

### ISSUE THREAD

**Issue by DavidVentura** [cy384/ppk_usb#6]
Hi
I have an original arduino leonardo which I'll try to use to test this with my v3 PPK.. thing is I have up to Pin 13. Following this:

MISO, MOSI and SCK:
First there is an SPI header on the Leonardo board. The pins connected to the SPI header are MISO (PB3), MOSI (PB2) and SCK (PB1). If you want to use them as I/O pins here is a secret. You can use them same as any other digital pin on Leonardo. Use the corresponding digital pin number:
MISO as digital pin 14
MOSI as digital pin 16
SCK as digital pin 15

I get that  I should use the SCK pin (upper middle) on the  SPI header
 Thanks

**Comment by DavidVentura** [comment]
Well, I couldn't wait. Yes, the SCK pin works. I am typing from my new PPK!

**Comment by cy384** [comment]
Great to hear you've got it working, enjoy!

For the record, the exact pins used aren't critical, you could probably tweak the code to use most other pins instead.
