### ISSUE TITLE
Making it work on ATMega328

### ISSUE THREAD

**Issue by DavidVentura** [cy384/ppk_usb#7]
Do you believe this should work on a 328? I can get them for 6USD where I am and the 32u4 costs 24USD. 
It seems able to work as a HID device and has software serial compatibility

**Comment by cy384** [comment]
The smaller arduinos/atmega devices can do hacky low-speed USB, but you'd still need a few more parts (zener diodes, etc.), and the code for this project would need to be adapted.  So, probably possible in a technological sense, but it would take more work and experimentation.
