### ISSUE TITLE
can I use the original palm connector

### ISSUE THREAD

**Issue by rhubarb** [cy384/ppk_usb#8]
Hi I'm very interested in reviving my PPK from the brick-like hibernation it's been in since I upgraded from a Palm V to a Tungsten oh many moons ago. But I don't have access to a 3D printer.
I _do_ still have my Palm V that the keyboard worked with. Can I pull out it's connector and use it instead?

**Comment by cy384** [comment]
Last time I looked (I may be wrong), the connector piece of a Palm V was not a nice independent module that you could pull out, and was pretty integrated into the rest of the hardware.  If you're not worried about making a nicely removable adapter, you could do something like soldering directly to the connector pins on the keyboard.
